services:
  wallet-postgres:
    image: postgres:16-alpine
    container_name: wallet-postgres
    environment:
      POSTGRES_DB: wallet_db
      POSTGRES_USER: wallet_app
      POSTGRES_PASSWORD: wallet_app_pw
    ports:
      - "5432:5432"
    volumes:
      - wallet_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U wallet_app -d wallet_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  wallet_postgres_data:
