package com.paymentplatform.wallet.domain;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.PrePersist;
import jakarta.persistence.PreUpdate;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

import java.time.Instant;

/**
 * A registered customer. Identified by a 10-digit CIF (the primary key, generated by the
 * client at sign-up). Wallets live in the {@code wallet} table and are linked back here by
 * CIF. The password is stored only as a PBKDF2 hash - see {@code PasswordHasher}.
 */
@Entity
@Table(
        name = "customer_master",
        uniqueConstraints = @UniqueConstraint(name = "uk_customer_master_email", columnNames = "email")
)
public class Customer {

    @Id
    @Column(name = "cif", length = 10, nullable = false, updatable = false)
    private String cif;

    @Column(name = "first_name", length = 64, nullable = false)
    private String firstName;

    @Column(name = "last_name", length = 64, nullable = false)
    private String lastName;

    /** Stored lower-cased; unique across all customers. */
    @Column(name = "email", length = 256, nullable = false)
    private String email;

    /** {@code pbkdf2$<iterations>$<salt-b64>$<hash-b64>} - never the raw password. */
    @Column(name = "password_hash", length = 512, nullable = false)
    private String passwordHash;

    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;

    protected Customer() {
    }

    public Customer(String cif, String firstName, String lastName, String email, String passwordHash) {
        this.cif = cif;
        this.firstName = firstName;
        this.lastName = lastName;
        this.email = email;
        this.passwordHash = passwordHash;
    }

    @PrePersist
    void onCreate() {
        Instant now = Instant.now();
        this.createdAt = now;
        this.updatedAt = now;
    }

    @PreUpdate
    void onUpdate() {
        this.updatedAt = Instant.now();
    }

    public String getCif() {
        return cif;
    }

    public String getFirstName() {
        return firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public String getEmail() {
        return email;
    }

    public String getPasswordHash() {
        return passwordHash;
    }

    public Instant getCreatedAt() {
        return createdAt;
    }

    public Instant getUpdatedAt() {
        return updatedAt;
    }
}
